[package]
name = "lumina-rust-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
juniper = "0.15.10"
postgrest = "1.0"
tokio = { version = "1.24.1", features = ["rt-multi-thread", "macros"] }
lambda_http = { version = "0.7", default-features = false, features = ["apigw_http"] }
lambda_runtime = "0.7"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
diesel = { version = "2.0.2", features = ["postgres", "r2d2"] }
serde_json = "1.0.91"
serde = "1.0.152"

