--
-- Name: applications; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.applications (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    application jsonb NOT NULL,
    application_type character varying NOT NULL
);


--
-- Name: bank; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.bank (
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    account_number text NOT NULL,
    id bigint NOT NULL
);


--
-- Name: bank_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.bank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.courses (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name character varying DEFAULT ''::character varying NOT NULL,
    slug text NOT NULL
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.transactions (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    amount numeric,
    "from" bigint,
    "to" bigint
);


--
-- Name: units; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.units (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name character varying DEFAULT ''::character varying NOT NULL,
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    parent_unit uuid,
    course_id uuid NOT NULL,
    slug text NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    email character varying NOT NULL,
    joined timestamp with time zone DEFAULT now() NOT NULL,
    password character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    calling_code character varying NOT NULL,
    country_code character varying NOT NULL,
    phone_number character varying NOT NULL,
    role character varying,
    object_id character varying,
    referrer uuid,
    referrer_mongo character varying
);
