name: deploy_api
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: production
    # choose production if branch is main
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        continue-on-error: true
      - name: Install libssl
        run: sudo apt install pkg-config && sudo apt install libssl-dev
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.10.0
      - name: Install Cargo Lambda
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-lambda
          version: "0.16"
      - name: Load Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install diesel_cli
        run: cargo install diesel_cli --no-default-features --features postgres
      - name: Run database migration
        run: diesel migration run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Print database schema
        run: diesel print-schema > src/models/schema.rs
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Build
        run: cargo lambda build --release --arm64

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
        # we might want to zip here instead of deploying as a binary
      - name: lambda-version
        run: cargo lambda --version
      - name: Deploy
        run: |
          cargo lambda deploy \
            --iam-role arn:aws:iam::739724808938:role/cargo-lambda-role-33666a7a-7c5e-483b-8134-62c4b305e4d6 \
            --env-var DATABASE_URL=$DATABASE_URL \
            --env-var JWT_SECRET=$JWT_SECRET \
            --env-var STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY \
            --env-var OPENAI_KEY=$OPENAI_KEY \
            --binary-name graph-api \
            graph-api-${GITHUB_REF##*/}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}