//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::applications::Entity as Applications;
pub use super::oauth_apps::Entity as OauthApps;
pub use super::oauth_grants::Entity as OauthGrants;
pub use super::question_assessments::Entity as QuestionAssessments;
pub use super::unit_progress::Entity as UnitProgress;
pub use super::users::Entity as Users;
